### ISSUE TITLE
PreparedQueuePair Issue

### ISSUE THREAD

**Issue by kyrie06** [jonhoo/rust-ibverbs#37]
// on host 1
let pqp: PreparedQueuePair = ...;
let host1end = pqp.endpoint();
host2.send(host1end);
let host2end = host2.recv();
let qp = pqp.handshake(host2end);

// on host 2
let pqp: PreparedQueuePair = ...;
let host2end = pqp.endpoint();
host1.send(host2end);
let host1end = host1.recv();
let qp = pqp.handshake(host1end);

According to my understanding, host 1 and host2 are bound to a process respectively. What work are done in the above, send and recv respectively, and how to use host2.send and recv on the process of host 1

**Comment by jonhoo** [comment]
This isn't really a well-suited support forum for how to use ibverbs more broadly. You could try reaching out to one of the active users in https://github.com/jonhoo/rust-ibverbs/issues/22 perhaps?
